# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zg53iHXptv7VWPjye2dU7Mi6OiWktdVr
"""

from captcha.image import ImageCaptcha
image = ImageCaptcha()

image_data = image.generate('TAVISH ARORA')
image.write('TAVISH ARORA', 'captcha.png')

#generate audio captcha
from captcha.audio import AudioCaptcha

audio = AudioCaptcha()
audio_data = audio.generate('45678')
audio.write('45678', 'audio.wav')

pip install captcha